# Generated by Django 2.2.16 on 2020-10-15 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblogaji', '0005_auto_20201015_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='myblogaji.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(related_name='posts', to='myblogaji.Tag'),
        ),
    ]
